version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dpm
    volumes:
      - ./.docker/database:/var/lib/mysql
    ports:
      - 33060:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080