version: '3.1'
 
services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: dpm
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: