name: Verify, Test & Publish code

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: packages/frontend/dist
          retention-days: 1

      - name: Test unit
        run: npm run test:unit

      - name: Test e2e
        run: npm run test:e2e:ci
  
  deploy:
    runs-on: ubuntu-latest
    needs: [verify]

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: packages/frontend/dist

      - name: Print build directory
        run: |
          ls packages/frontend/dist
          
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_BAY_064C4C303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "packages/frontend"
          output_location: "dist"
          skip_app_build: true

