name: Verify, Test & Publish code

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive frontend build output
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: packages/frontend/dist
          retention-days: 1
      
      - name: Archive backend build output
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: packages/backend/dist
          retention-days: 1

      - name: Test unit
        run: npm run test:unit

      - name: Test e2e
        run: npm run test:e2e:ci
  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [verify]

    steps:
      - uses: actions/checkout@v3

      - name: Download frontend build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: packages/frontend/dist

      - name: Install SWA
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy Azure Static Web App
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          APP_NAME: ${{ secrets.SWA_CLI_APP_NAME }}
          RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

        run: swa deploy -O ./packages/frontend/dist -a ./packages/frontend -i ./packages/backend -d $DEPLOYMENT_TOKEN -S $SUBSCRIPTION_ID -T $TENANT_ID -n $APP_NAME -R $RESOURCE_GROUP
          

